# This is a basic workflow to help you get started with Actions

name: Add To GitHub tasks project

# Controls when the workflow will run
on:
  issues:
    types:
      - opened 


jobs:
  add-to-project:
    name: Add Issue to project tasks 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          # URL of the project to add issues to
          project-url: https://github.com/orgs/excelerate-america/projects/24
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # A comma-separated list of labels to use as a filter for issue to be added
          labeled: TASK
